### ISSUE TITLE
feat: Upload individual artifacts to Google Cloud Storage

### ISSUE THREAD

**Issue by mattes** [pluto/web-prover-circuits#92]
**Motivation**

For a **Chrome extension** running inside the browser, we leverage the browser’s ability to decompress files during transit. By including the Accept-Encoding: gzip header in requests, Chrome will automatically handle gzipped files. Files uploaded to Google Cloud Storage with a Content-Type of application/xyz and Content-Encoding of gzip will be served in their compressed form. This approach requires the extension to request files individually, as the browser cannot unpack an entire directory structure. The browser gives us the decompression logic for free.

For the **mobile app or CLI**, the responsibility of decompression shifts to the application. To simplify implementation, the app should also request individual gzipped files instead of dealing with directory unpacking. Gzip remains an effective and efficient choice for this purpose.

**Todos**
- [x] Update Github Actions to only gzip the required files, see below.
- [x] Artifacts are required by the Release Github actions, but expire after 5 days. Maybe just rebuild from scratch during release?
- [x] Introduce Github Action to upload to Google Cloud Storage bucket.

**Required files** (via [Slack](https://plutoxyz.slack.com/archives/C03D5FC2ARE/p1736970073968979?thread_ts=1736969489.463499&cid=C03D5FC2ARE))
```
- serialized_setup_512.bytes
- http_verification_512b.r1cs
- json_extraction_512b.r1cs
- plaintext_authentication_512b.r1cs
- http_verification_512b_js/http_verification_512b.wasm
- json_extraction_512b_js/json_extraction_512b.wasm
- plaintext_authentication_512b_js/plaintext_authentication_512b.wasm
```

**Comment by mattes** [comment]
@Autoparallel, Tracy mentioned you started work on this. Let's huddle.

**Comment by mattes** [comment]
Github Actions to use:

```
# docs: https://github.com/google-github-actions/auth?tab=readme-ov-file
- uses: 'google-github-actions/auth@v2'
  with:
    project_id: 'web-prover-circuits-fa4cf3'
    workload_identity_provider: 'projects/530011589985/locations/global/workloadIdentityPools/github/providers/web-prover-circuits'

# docs: https://github.com/google-github-actions/upload-cloud-storage
- uses: 'google-github-actions/upload-cloud-storage@v2'
  with:
    path: 'artifacts' # TODO folder which has the files
    destination: 'web-prover-circuits.pluto.xyz/$VERSION'  # TODO version
    parent: false
    gzip: false # already gzipped
    headers: |-
       content-type: 'application/octet-stream' # what is the actual mime type of the files?
       content-encoding: 'gzip'
```
